language: node_js
sudo: false
node_js:
- '6.2'
- '5.12'
after_success: cat .coverage/lcov.info | ./node_modules/coveralls/bin/coveralls.js
deploy:
  on:
    branch: master
  provider: npm
  email: lucassus@gmail.com
  api_key:
    secure: R9Bx26CeIxEMw/cWel0JYqp452QrbTSzz6AP2GMEIaYIfTIYn8yt5z3LoZMPJ2bRo2WZu658KZbuTcOsPX+v/95pc/CjIoGoDjHXvqPYIP0waXEgDuxsy9IwZQR0fcn6DqSyAq4IuyLMqf8HWmlqNfdANPMIXkt1S8WZ3f+xuh0=
